#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : speedtest-cli
Version  : 2.1.2
Release  : 5
URL      : https://files.pythonhosted.org/packages/5c/c8/296057f78f16721863f9edb5abdb0d2648c5c6932697f29d80d920fdcd91/speedtest-cli-2.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/5c/c8/296057f78f16721863f9edb5abdb0d2648c5c6932697f29d80d920fdcd91/speedtest-cli-2.1.2.tar.gz
Summary  : Command line interface for testing internet bandwidth using speedtest.net
Group    : Development/Tools
License  : Apache-2.0
Requires: speedtest-cli-bin = %{version}-%{release}
Requires: speedtest-cli-license = %{version}-%{release}
Requires: speedtest-cli-python = %{version}-%{release}
Requires: speedtest-cli-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=============
        
        Command line interface for testing internet bandwidth using
        speedtest.net

%package bin
Summary: bin components for the speedtest-cli package.
Group: Binaries
Requires: speedtest-cli-license = %{version}-%{release}

%description bin
bin components for the speedtest-cli package.


%package license
Summary: license components for the speedtest-cli package.
Group: Default

%description license
license components for the speedtest-cli package.


%package python
Summary: python components for the speedtest-cli package.
Group: Default
Requires: speedtest-cli-python3 = %{version}-%{release}

%description python
python components for the speedtest-cli package.


%package python3
Summary: python3 components for the speedtest-cli package.
Group: Default
Requires: python3-core
Provides: pypi(speedtest_cli)

%description python3
python3 components for the speedtest-cli package.


%prep
%setup -q -n speedtest-cli-2.1.2
cd %{_builddir}/speedtest-cli-2.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583696929
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/speedtest-cli
cp %{_builddir}/speedtest-cli-2.1.2/LICENSE %{buildroot}/usr/share/package-licenses/speedtest-cli/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/speedtest
/usr/bin/speedtest-cli

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/speedtest-cli/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
